services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: atomic
      POSTGRES_PASSWORD: atomic
      POSTGRES_DB: atomic_goals
    volumes:
      - atomic-pg-data:/var/lib/postgresql/data

volumes:
  atomic-pg-data:
